update workflow train_model

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -17,22 +17,24 @@ jobs:
       - name: Check CSV file modification
         id: check_files
         run: |
-            CSV_FILE="SignLingo/app/data/keypoint_classifier/keypoint.csv"
-            git fetch --depth=1
+            CSV_FILE="app/data/keypoint_classifier/keypoint.csv"
+            git fetch
             LAST_COMMIT_TOUCHING_CSV=$(git log -1 --format="%at" -- $CSV_FILE)
             
             if [ -z "$LAST_COMMIT_TOUCHING_CSV" ]; then
-            echo "No commits found affecting $CSV_FILE. Assuming new or untracked file."
-            echo "train_model=true" >> $GITHUB_ENV
-            else
-            CURRENT_TIME=$(date +%s)
-            TIME_SINCE_LAST_CHANGE=$(($CURRENT_TIME - $LAST_COMMIT_TOUCHING_CSV))
-            echo "Time since last commit affecting CSV: $TIME_SINCE_LAST_CHANGE seconds"
-            if [ $TIME_SINCE_LAST_CHANGE -gt 0 ]; then
-                echo "train_model=true" >> $GITHUB_ENV
-            else
-                echo "train_model=false" >> $GITHUB_ENV
+              echo "No recent commits affecting $CSV_FILE found."
+              exit 1
             fi
+            
+            CURRENT_TIME=$(date +%s)
+            TIME_SINCE_LAST_CHANGE=$((CURRENT_TIME - LAST_COMMIT_TOUCHING_CSV))
+            
+            echo "Time since last commit affecting CSV: $TIME_SINCE_LAST_CHANGE seconds"
+            
+            if [ $TIME_SINCE_LAST_CHANGE -gt 0 ]; then
+              echo "Training model required."
+            else
+              echo "No training required."
             fi
 
   train:
